name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: tibdex/github-app-token@v1.8.2
#        if: ${{ !env.ACT }}
#        id: create-app-token
#        with:
#          app_id: ${{ secrets.APP_ID }}
#          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        if: ${{ !env.ACT }}
 #       with:
 #         token: ${{ steps.create-app-token.outputs.token }}
      - name: setup git
        run: |
          git config user.name "zhbjzhql1"
          git config user.email "zhbjzhql@qq.com"
      - uses: actions/setup-node@v3
        if: ${{ !env.ACT }}
        with:
          node-version: 18
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: check *.channels.xml
        run: |
          npm run channels:lint
      - name: generate .api/guides.json
        run: npm run api:generate
      - run: git status
      - name: move .api/guides.json to zhbjzhql1/api
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository-name: zhbjzhql1/api
          branch: gh-pages
          folder: .api
#          token: ${{ steps.create-app-token.outputs.token }}
          git-config-name: zhbjzhql1
          git-config-email: zhbjzhql@qq.com
          commit-message: '[Bot] Deploy to zhbjzhql1/api'
          clean: false
